# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Bakhuzet
tagline:             'Random short stories'
description:         'Short stories and ideas'
url:                 http://joshuasemple.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joshua Semple
  github:            https://github.com/JoshuaSemple
  url:               http://joshuasemple.github.io
  email:

plugins: [jekyll-paginate]

# Custom vars
version:             1.0.0
